### ISSUE TITLE
npx create-ima-app imajs-tutorial error

### ISSUE THREAD

**Issue by maxbertinetti** [seznam/ima#104]
`➜ npx create-ima-app imajs-tutorial
Need to install the following packages:
  create-ima-app
Ok to proceed? (y)
? Choose a template for your new IMA.js application: Empty - The basic Hello World example. Ideal for new projects.

info: Creating new IMA.js app inside imajs-tutorial directory...
info: Creating basic directory structure...
info: Running npm install inside app directory, this might take a while...
      Press CTRL+C to cancel.

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@16.12.0
npm ERR! node_modules/react
npm ERR!   react@"16.12.0" from the root project
npm ERR!   peer react@"16.x" from @ima/core@17.10.0
npm ERR!   node_modules/@ima/core
npm ERR!     @ima/core@"17.10.0" from the root project
npm ERR!     peer @ima/core@"17.x" from @ima/plugin-hot-reload@0.1.0
npm ERR!     node_modules/@ima/plugin-hot-reload
npm ERR!       @ima/plugin-hot-reload@"0.1.0" from the root project
npm ERR!   3 more (react-dom, enzyme-adapter-react-16, enzyme-adapter-utils)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.14.0" from react-test-renderer@16.14.0
npm ERR! node_modules/enzyme-adapter-react-16/node_modules/react-test-renderer
npm ERR!   react-test-renderer@"^16.0.0-0" from enzyme-adapter-react-16@1.15.1
npm ERR!   node_modules/enzyme-adapter-react-16
npm ERR!     dev enzyme-adapter-react-16@"1.15.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/max/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/max/.npm/_logs/2021-04-27T09_42_51_039Z-debug.log
(node:41781) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: npm install
    at makeError (/Users/max/.npm/_npx/5c90cf034c3aec33/node_modules/execa/lib/error.js:56:11)
    at Function.module.exports.sync (/Users/max/.npm/_npx/5c90cf034c3aec33/node_modules/execa/index.js:188:17)
    at createImaApp (/Users/max/.npm/_npx/5c90cf034c3aec33/node_modules/create-ima-app/scripts/create.js:104:9)
    at /Users/max/.npm/_npx/5c90cf034c3aec33/node_modules/create-ima-app/scripts/create.js:44:3
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:41781) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
`

So I cd in the directory and npm install --force and seems to work

**Comment by mjancarik** [comment]
Hi,

Could you send me node and npm versions?

**Comment by maxbertinetti** [comment]
~
➜ node -v
v14.16.0

~
➜ npm -v
7.6.3

**Comment by mjancarik** [comment]
I have almost same configuration. I think that problem will be in npm@7. We support node@14 and npm@6 in ima@17.

**Comment by maxbertinetti** [comment]
I will try downgrading npm.
But if possible I wont to use npm@15 or 16 on my Apple M1 Silicon.
I will try in the w.e. and let you know.

**Comment by maxbertinetti** [comment]
I can confirm installation works with node@12 or 14 and npm@6
