### ISSUE TITLE
managedRootView cannot be changed

### ISSUE THREAD

**Issue by lastuvka** [seznam/ima#40]
ManagedRootView is set in ViewAdapter constructor (https://github.com/seznam/ima/blob/master/packages/core/src/page/renderer/ViewAdapter.js#L47) from here - https://github.com/seznam/ima/blob/master/packages/core/src/page/renderer/AbstractPageRenderer.js#L185 but only first time  when in route options is an other managedRootView - there is no option to change it. There should be something like -  $pageView in getDerivedStateFromProps.

**Comment by mjancarik** [comment]
I think that you can change managedRootView but Renderer unmount old component from DOM and mount new one.
