### ISSUE TITLE
Not store pageView in state - only in props

### ISSUE THREAD

**Issue by lastuvka** [seznam/ima#41]
This issue is connected with https://github.com/seznam/ima/issues/40

Possible solution is remove https://github.com/seznam/ima/blob/master/packages/core/src/page/renderer/ViewAdapter.js#L10 and in ViewAdapter's render method https://github.com/seznam/ima/blob/master/packages/core/src/page/renderer/ViewAdapter.js#L90 push to createElement correct ManageRootView from props and state extended with pageView from props.

**Comment by mjancarik** [comment]
We will solve this problem in IMA@18.
