### ISSUE TITLE
Do redirect in debug mode

### ISSUE THREAD

**Issue by vaclav-pur** [seznam/ima#468]
If I use `router.redirect` with `debug` mode set to `true` I get error, but page won't redirect to new url. It would be great to redirect even with debug mode on.

**Comment by jsimck** [comment]
Do you have any reproducible example? I don't think we throw any errors in redirect in $Debug mode currently so this should not happen.

**Comment by vaclav-pur** [comment]
I do, I'll PM, it's in internal network 😉

**Comment by jsimck** [comment]
Will be fixed in IMA@19 -> https://github.com/seznam/ima/pull/470
